### ISSUE TITLE
Usability Issues

### ISSUE THREAD

**Issue by mrentsch65** [robinziegler/TINF21C_Team4_Modelling_Wizard_Improvements#111]
1. Ich kann diese obere Sektion nicht zuordnen.
2. Responsiveness: Verändern der Dialogbreite löscht den Dialoginhalt.
3. Die Mandatory Parameter sollten markiert sein wie bei der alten Software.
4. Die beiden Icons scheinen redundant zueinander zu sein. Ich würde anstelle des Hamburgers den Pfeil verwenden.
5. 
![image](https://user-images.githubusercontent.com/50681355/236611013-13be8c0e-ac1b-4afd-978d-6bfda279e4ca.png)

**Comment by mrentsch65** [comment]
Im eingeklappten Zustand wird der Text abgeschnitten. Wie wäre es, statt dessen im eingeklappten Zustand Icons anzuzeigen?

![image](https://user-images.githubusercontent.com/50681355/236611382-1fd4b0fa-0a32-4de7-982c-6dfa5cb1136c.png)

**Comment by mrentsch65** [comment]
Nach dem Laden einer Datei muss ich 3 Klicks machen, bis ich Inhalte angezeigt bekomme. Das sollte per Default geöffnet werden:
![image](https://user-images.githubusercontent.com/50681355/236611567-24624fcf-bd20-4329-a64d-336dae8a2a50.png)

**Comment by mrentsch65** [comment]
Nach "File - New" wird der zuvor verwendete Dateiname weiter angezeigt und verwendet:

![image](https://user-images.githubusercontent.com/50681355/236611831-62c79a01-f781-4fd3-bb37-504737c66d8a.png)

**Comment by mrentsch65** [comment]
Wozu benötigt man den Reiter "Generic Data" ? Den kann man weglassen.
![image](https://user-images.githubusercontent.com/50681355/236611991-6c7de49c-bfa5-4c4d-8b94-051ce526168a.png)

**Comment by mrentsch65** [comment]
Hinter dem Reiter "Interfaces" befindet sich keine Funktion:

![image](https://user-images.githubusercontent.com/50681355/236612063-c3cc31ec-84bc-4d72-922a-dde634dfc02e.png)

Dort sollte es die Möglichkeit "Add Interfaces" geben.

**Comment by mrentsch65** [comment]
Was passiert, wenn man unter "Libraries" etwas auswählt? Es ist keine Auswirkung ersichtlich.

**Comment by maximiliantrumpp** [comment]
> 1. Ich kann diese obere Sektion nicht zuordnen.
> 2. Responsiveness: Verändern der Dialogbreite löscht den Dialoginhalt.
> 3. Die Mandatory Parameter sollten markiert sein wie bei der alten Software.
> 4. Die beiden Icons scheinen redundant zueinander zu sein. Ich würde anstelle des Hamburgers den Pfeil verwenden.
> 
> ![image](https://user-images.githubusercontent.com/50681355/236611013-13be8c0e-ac1b-4afd-978d-6bfda279e4ca.png)

Guten Tag Herr Rentschler,
die erste Zeile wird wie der Rest direkt aus der gewählten Libary geladen. 
Bei dem zweiten Fehler handelt es demnach um einen Bug, das beim Ändern der Größe der Inhalt zusammengelappt wird.
Wir versuchen die Zeilen farblich zu markieren und die redundanten Icons zu entfernen.

**Comment by maximiliantrumpp** [comment]
> Im eingeklappten Zustand wird der Text abgeschnitten. Wie wäre es, statt dessen im eingeklappten Zustand Icons anzuzeigen?

Hierfür habe ich gerade ein Issue erstellt.

**Comment by maximiliantrumpp** [comment]
> Nach dem Laden einer Datei muss ich 3 Klicks machen, bis ich Inhalte angezeigt bekomme. Das sollte per Default geöffnet werden: ![image](https://user-images.githubusercontent.com/50681355/236611567-24624fcf-bd20-4329-a64d-336dae8a2a50.png)
> 
> Im Header wird fälschlicherweise "[unloaded]" angezeigt.

Hierfür habe ich gerade ein Issue erstellt.

**Comment by maximiliantrumpp** [comment]
> Wozu benötigt man den Reiter "Generic Data" ? Den kann man weglassen. ![image](https://user-images.githubusercontent.com/50681355/236611991-6c7de49c-bfa5-4c4d-8b94-051ce526168a.png)

Generic Data wurde im neusten Release zu Role Classes umbenannt. Bitte entschuldigen Sie eventuelle Verwirrungen.

**Comment by maximiliantrumpp** [comment]
> Hinter dem Reiter "Interfaces" befindet sich keine Funktion:
> 
> ![image](https://user-images.githubusercontent.com/50681355/236612063-c3cc31ec-84bc-4d72-922a-dde634dfc02e.png)
> 
> Dort sollte die Funktion "Add Interface" angeboten werden.

Diese Funktion wurde im neusten Release hinzugefügt.

**Comment by maximiliantrumpp** [comment]
> Was passiert, wenn man unter "Libraries" etwas auswählt? Es ist keine Auswirkung ersichtlich.

Durch eine Auswahl ändern sich die Optionen beim Hinzufügen einer System Unit Class, Role Class oder eines Interfaces.

**Comment by mrentsch65** [comment]
Aktuelle Versionsnummer und Builddate wird nicht angezeigt:

![image](https://user-images.githubusercontent.com/50681355/237015115-03bb008a-39cf-4961-8e0b-1b6f9acae777.png)

Bitte dynamisieren (d.h. nicht hartcodiert im Sourcecode)!

**Comment by mrentsch65** [comment]
> > Hinter dem Reiter "Interfaces" befindet sich keine Funktion:
> > ...
> > Dort sollte die Funktion "Add Interface" angeboten werden.
> 
> Diese Funktion wurde im neusten Release hinzugefügt.

Warum wurde die Usability nicht einheitlich zu "Add Attachement" gestaltet?
![image](https://user-images.githubusercontent.com/50681355/237016512-181a87d4-1234-4eda-807d-a69491881e83.png)

![image](https://user-images.githubusercontent.com/50681355/237016673-a01573cb-7b0c-4233-ba33-c808266e6453.png)

**Comment by mrentsch65** [comment]
> > Was passiert, wenn man unter "Libraries" etwas auswählt? Es ist keine Auswirkung ersichtlich.
> 
> Durch eine Auswahl ändern sich die Optionen beim Hinzufügen einer System Unit Class, Role Class oder eines Interfaces.

Das ist aber für den Anwender komplett undurchschaubar.

**Comment by maximiliantrumpp** [comment]
> > > Was passiert, wenn man unter "Libraries" etwas auswählt? Es ist keine Auswirkung ersichtlich.
> > 
> > 
> > Durch eine Auswahl ändern sich die Optionen beim Hinzufügen einer System Unit Class, Role Class oder eines Interfaces.
> 
> Das ist aber für den Anwender komplett undurchschaubar.

Das wurde bereits behoben und ist im nächsten Release implementiert.

**Comment by maximiliantrumpp** [comment]
> 
Bearbeiten wir und implementieren wir im nächsten Relaese.
