### ISSUE TITLE
"File -Open" does not work for AML and EDZ

### ISSUE THREAD

**Issue by mrentsch65** [robinziegler/TINF21C_Team4_Modelling_Wizard_Improvements#145]
It only works for AMLX-files! A reason for the error is not displayed in the modal:
![image](https://github.com/robinziegler/TINF21C_Team4_Modelling_Wizard_Improvements/assets/50681355/a1d96182-ba5d-46bd-9ea4-31de5298c0ec)

The [Saved] state is in my opinion not correct and misleading. Either nothing should be shown or for example [New] or [Unsaved].

**Comment by maximiliantrumpp** [comment]
Unfortunately, there was a bug in the last release which prevented AML and EDZ files from being opened. This has been fixed in the current release (version 1.0.1). In addition, the label "unsaved" was added when opening the file.
