### ISSUE TITLE
Usability analysis of previous team

### ISSUE THREAD

**Issue by DanaFrey** [robinziegler/TINF21C_Team4_Modelling_Wizard_Improvements#29]
Please complete and upload (here) the checklist to the usability analysis below. If possible let your student colleagues or your family members complete the checklist too. The more opinions we get on the program, the better. Note: this checklist only focusses on the work of the Team TINF20C_ModellingWizard_Devices !

[TINF21C_Usability_Analysis_Team_4.docx](https://github.com/robinziegler/TINF21C_Team4_Modelling_Wizard_Improvements/files/9886792/TINF21C_Usability_Analysis_Team_4.docx)

**Comment by DanaFrey** [comment]
[TINF21C_Usability_Analysis_Team_4.docx](https://github.com/robinziegler/TINF21C_Team4_Modelling_Wizard_Improvements/files/9886574/TINF21C_Usability_Analysis_Team_4.docx)

**Comment by maximiliantrumpp** [comment]
[TINF21C_Usability_Analysis_Team_4_Max.pdf](https://github.com/robinziegler/TINF21C_Team4_Modelling_Wizard_Improvements/files/9886654/TINF21C_Usability_Analysis_Team_4_Max.pdf)

**Comment by michi3214** [comment]
[TINF21C_Usability_Analysis_Team_4_Michael.pdf](https://github.com/robinziegler/TINF21C_Team4_Modelling_Wizard_Improvements/files/9965041/TINF21C_Usability_Analysis_Team_4_Michael.pdf)

**Comment by DanaFrey** [comment]
[TINF21C_Usability_Analysis_Team_4_Dana.pdf](https://github.com/robinziegler/TINF21C_Team4_Modelling_Wizard_Improvements/files/9973413/TINF21C_Usability_Analysis_Team_4_Dana.pdf)

**Comment by Fabiankreuzer** [comment]
[TINF21C_Usability_Analysis_Team_4_Fabian.docx](https://github.com/robinziegler/TINF21C_Team4_Modelling_Wizard_Improvements/files/9975255/TINF21C_Usability_Analysis_Team_4_Fabian.docx)

**Comment by Fabiankreuzer** [comment]
[TINF21C_Usability_Analysis_Team_4_Fabian.pdf](https://github.com/robinziegler/TINF21C_Team4_Modelling_Wizard_Improvements/files/9975257/TINF21C_Usability_Analysis_Team_4_Fabian.pdf)

**Comment by HoffmannNils** [comment]
[TINF21C_Usability_Analysis_Team_4_Summary.docx](https://github.com/robinziegler/TINF21C_Team4_Modelling_Wizard_Improvements/files/10993580/TINF21C_Usability_Analysis_Team_4_Summary.docx)

**Comment by HoffmannNils** [comment]
[TINF21C_Usability_Analysis_Team_4_Summary.pdf](https://github.com/robinziegler/TINF21C_Team4_Modelling_Wizard_Improvements/files/10994350/TINF21C_Usability_Analysis_Team_4_Summary.pdf)
