### ISSUE TITLE
Conversion rules for test and documentation of the EDZ-Fileimport

### ISSUE THREAD

**Issue by mrentsch65** [robinziegler/TINF21C_Team4_Modelling_Wizard_Improvements#30]
**The following elements should be used for nameplate information**

If present, P_PART_ADDRESS_LONGNAME shall be used for **Manufacturer**. Otherwise P_ARTICLE_MANUFACTURER, which should have the same content as P_PART_ADDRESS_SHORTNAME.

P_PART_ADDRESS_NOTE shall be used for **ManufacturerURI**, if it contains a valid URL.
P_ARTICLE_DESCR1 shall be used for **DeviceClass**.
P_ARTICLE_TYPENR shall be used for **Model**.
P_ARTICLE_ORDERNR should be used for **ProductCode**.

P_ARTICLE_PICTUREFILE should be used for **ComponentPicture**.

**The following elements should be used for CommercialData/ManufacturerDetails:**

P_PART_ADDRESS_NAME1 	Address1
P_PART_ADDRESS_STREET 	Address2
P_PART_ADDRESS_TOWN  	City
P_PART_ADDRESS_ZIPTOWN	ZipCode
P_PART_ADDRESS_STATE 	Country
P_PART_ADDRESS_EMAIL	ContactMail
P_PART_ADDRESS_PHONE 	ContactPhone
P_PART_ADDRESS_FAX	

**The following elements should be used for the elements of GeneralTechnicalData:**

P_ARTICLE_WEIGHT	Weight
P_ARTICLE_DEPTH	Length
P_ARTICLE_HEIGHT	Height
P_ARTICLE_WIDTH	Width
P_ARTICLE_NOTE	DescriptionShort
P_ARTICLE_DESCR2	DescriptionLong

**For ElectricInterfaces, the following rules apply:**

```
<functiontemplate connectiondescription="RxD" connectionDesignation="1" functiondefcategory="1302" functiondefgroup="1" functiondefid="1" hasled="0" hasplugadapter="0" intrinsicsafety="0" pos="2" safetyrelevant="0" terminalfunction="0" terminalNr="DATA"/>

<functiontemplate connectiondescription="TxD" connectionDesignation="2" functiondefcategory="1302" functiondefgroup="1" functiondefid="1" hasled="0" hasplugadapter="0" intrinsicsafety="0" pos="3" safetyrelevant="0" terminalfunction="0" terminalNr="DATA"/>
```

**terminalNr** identifies a connector name, whereas **connetionDesignation** a single pin position within this connector. **connectionDescription** is then the name of the pin. This should translate to:

```
**<ExternalInterface Name="DATA" ID="GUID1"
 RefBaseClassPath="AutomationMLComponentBaseICL/ElectricInterface">
<ExternalInterface Name="1" ID=" GUID2"
   RefBaseClassPath="AutomationMLComponentBaseICL/ElectricInterface">
   <Attribute Name="FunctionType" AttributeDataType="xs:string"
      RefAttributeType="GenericPinAttributeTypeLib/FunctionType">
      <Value>RxD</Value>
   </Attribute>
    </ExternalInterface>
    <ExternalInterface Name="2" ID=" GUID3"
       RefBaseClassPath="AutomationMLComponentBaseICL/ElectricInterface">
   <Attribute Name="FunctionType" AttributeDataType="xs:string"
      RefAttributeType="GenericPinAttributeTypeLib/FunctionType">
      <Value>TxD</Value>
   </Attribute>
     </ExternalInterface>
</ExternalInterface>**
```

**Comment by maximiliantrumpp** [comment]
The functionality to open EDZ files wasn't supported by the previous team, therefore this issue has a low priority.

**Comment by mrentsch65** [comment]
@maximiliantrumpp: EDZ file import was implemented and should remain. Did you not user the newest version of the software?
Otherwise the software would not be an improvement compared to the previous version.

**Comment by maximiliantrumpp** [comment]
> @maximiliantrumpp: EDZ file import was implemented and should remain. Did you not use the newest version of the software as basis?
> Otherwise the software would not be an improvement compared to the previous version.

Thank you for your reply. We will check this.

**Comment by Fabiankreuzer** [comment]
The EDZ file import is now at a state where we need to test it, but no test files where given. Therefore, this issue is now on hold.
