### ISSUE TITLE
New Usability Concept

### ISSUE THREAD

**Issue by sophiekirschner** [robinziegler/TINF21C_Team4_Modelling_Wizard_Improvements#33]
- reasoned description of UI/UX improvements
- Draft of UI/UX improvements

**Comment by maximiliantrumpp** [comment]
Properties of the UI/UX to be determined during the usability analysis:
For the menu design:
- Menu position: top or side
- App bar at the top of the application
- Short cuts for option in App bar?

For Genereic Data page:
- Move RoleClassLibary to ModalPage behind add button?
- Generic information and attributes view as rows or columns

For Interface page:
-Move Interface Class Libary to  ModalPage behind add button?
- Interface and attributes view as rows or columns

For Attachment page:
- Add attachment section behind add Button and Attachmentlist as Row
