### ISSUE TITLE
Create/Import Manual to GitHub Wiki

### ISSUE THREAD

**Issue by michi3214** [robinziegler/TINF21C_Team4_Modelling_Wizard_Improvements#37]
The Manual of the Modelling Wizard should be added to GitHub Wiki. 

- [x] Import the manual from the last project
- [x] Updating the manual to the new GUI
- [x] Add a topic/chapter about libraries and their usage
- [x] Add link in the about page 

After finish a new issue should be created to link the new manual in the Modlling Wizard (see comment from Maximilian Trumpp).

**Comment by maximiliantrumpp** [comment]
Please embed the url to the wiki into the Help SubModal View XAML. Currently the old wiki is embedded.

**Comment by michi3214** [comment]
Do not open the wiki in the applicaation. We should use an extern browser to open it.
