### ISSUE TITLE
Move "Load Library" to "Libraries" menu

### ISSUE THREAD

**Issue by DanaFrey** [robinziegler/TINF21C_Team4_Modelling_Wizard_Improvements#40]
![image](https://user-images.githubusercontent.com/96415701/226752366-4fd82ae2-30ce-4f52-9867-3ff503863411.png)

The function "Load Library", which is currently located in the "File" dropdown menu should be moved to the "Libraries" menu.

**Comment by maximiliantrumpp** [comment]
Already done.
