### ISSUE TITLE
Remove "About" from "Help" dropdown menu

### ISSUE THREAD

**Issue by DanaFrey** [robinziegler/TINF21C_Team4_Modelling_Wizard_Improvements#42]
![image](https://user-images.githubusercontent.com/96415701/226764497-882463b6-d4b6-4e89-bf93-9fab1b2f80cb.png)

**Comment by michi3214** [comment]
At the moment the MenuBarItem can't be used as button. See this Issue from WinUI [here](https://github.com/microsoft/microsoft-ui-xaml/issues/3011).


Alternatively, it could not be changed or each MenuBarItem gets an identical sub-item.



![Image](https://user-images.githubusercontent.com/93448865/226862677-7f8e64e7-8b35-4f6c-81a0-def52ee57f41.png)



![Image](https://user-images.githubusercontent.com/93448865/226863562-7c0caebe-1b34-4789-a2df-edda9cd36f33.png)

**Comment by michi3214** [comment]
After consultation with the customer, this functionality is not changed.
