### ISSUE TITLE
Editing "DataType"

### ISSUE THREAD

**Issue by DanaFrey** [robinziegler/TINF21C_Team4_Modelling_Wizard_Improvements#47]
In the "Attributes" table, the user can edit the "DataType" column which can lead to following problems. Dont let the user edit this input field.

![image](https://user-images.githubusercontent.com/96415701/226769005-8f05afa0-64a6-46ab-9765-4706e87a9516.png)

**Comment by michi3214** [comment]
Done by 50e1b683fb31c564464e54d3f21813c91536c29e
