### ISSUE TITLE
Delete Button for each line

### ISSUE THREAD

**Issue by DanaFrey** [robinziegler/TINF21C_Team4_Modelling_Wizard_Improvements#48]
![image](https://user-images.githubusercontent.com/96415701/226865612-f498cebe-0e06-4758-831f-a61e173b69c3.png)

You can currently find one delete button located on top of the table. It would be more pratical to have one delete button per line instead of one main button.

**Comment by maximiliantrumpp** [comment]
Maybe the delete option should be better implemented with a right-click.
