### ISSUE TITLE
Remove the two nav bars and create one general nav bar

### ISSUE THREAD

**Issue by DanaFrey** [robinziegler/TINF21C_Team4_Modelling_Wizard_Improvements#49]
![image](https://user-images.githubusercontent.com/96415701/226867013-69001480-ee2c-4bde-a5c5-c6cd6b77d315.png)

**Comment by maximiliantrumpp** [comment]
Already removed the two textfields.

**Comment by michi3214** [comment]
The input can only be done in the gernic data menu. The two textfields are deleted.
