### ISSUE TITLE
Light / Dark Theme

### ISSUE THREAD

**Issue by michi3214** [robinziegler/TINF21C_Team4_Modelling_Wizard_Improvements#61]
The apllication should have a button to switch the theme.
- [x] Add button for switching
- [x]  Images musst be changing the look 
- [x]  All texts must remain readable in both variants

**Comment by michi3214** [comment]
Button to toggle the theme is added by d839d5ea21fd06cca7213514f459bdf075c16d80 .

**Comment by maximiliantrumpp** [comment]
Fixed in commit abf8b24.
