### ISSUE TITLE
First Object must be a the system unit class 

### ISSUE THREAD

**Issue by michi3214** [robinziegler/TINF21C_Team4_Modelling_Wizard_Improvements#74]
The first object should be used for filename (manufactur and devicename).
The other objects should be under this item.
When it is a new file, it should greate this object. (Bevor implementation, implement the starting view)

**Comment by michi3214** [comment]
Maybe there should no delete button for this object.

**Comment by Fabiankreuzer** [comment]
Warten auf Rückmeldung vom Renschler zu separierung von Rollclases und System Unit Classes
