### ISSUE TITLE
Cannot Install

### ISSUE THREAD

**Issue by mrentsch65** [robinziegler/TINF21C_Team4_Modelling_Wizard_Improvements#86]
Installation ist because of IT policy not possible, certificates of the app need to be updated first:

![image](https://user-images.githubusercontent.com/50681355/233730335-f0979778-e6cf-4622-aa05-6cd2c943fe74.png)

**Comment by michi3214** [comment]
Guten Tag Herr Rentschler,
dieser Fehler ist uns bekannt und wurde in der Release Note ([hier](https://github.com/robinziegler/TINF21C_Team4_Modelling_Wizard_Improvements/releases/tag/Beta)) aufgelistet und kann mit der folgenden Anleitung gelöst :
[https://1techpc.de/so-beheben-sie-den-fehler-herausgeber-konnte-nicht-verifiziert-werden-unter-windows-11/](https://1techpc.de/so-beheben-sie-den-fehler-herausgeber-konnte-nicht-verifiziert-werden-unter-windows-11/)

Das Zertifikat kann manuell auf Ihrem Computer installiert werden. 
Bitte geben Sie uns einen kurze Rückmeldung, wenn das Problem so gelöst werden konnte.

Mit freundlichen Grüßen

**Comment by maximiliantrumpp** [comment]
> Installation ist because of IT policy not possible, certificates of the app need to be updated first:
> 
> ![image](https://user-images.githubusercontent.com/50681355/233730335-f0979778-e6cf-4622-aa05-6cd2c943fe74.png)
For a description of the installation please visit our [Wiki](https://github.com/robinziegler/TINF21C_Team4_Modelling_Wizard_Improvements/wiki/Instruction#add-certificate-for-the-modelling-wizard)

**Comment by mrentsch65** [comment]
Mit Ihrer Anleitung hat die Installation jetzt funktioniert. 
Allerdings kann ich nichts sinnvolles mit der Applikation machen.
"File"-"New" hat keine Auswirkungen.
"File"-"Open" lädt Bestandsdateien, zeigt aber nur die enthaltenen Rollenklassenbibliotheken. an. Richtig wäre die Anzeige der SystemUnitKlasse und deren Inhalte. Wenn die nicht in der Datei vorhanden ist, ist das grundsätzlich ein Fehler, der angezeigt werden muss.

**Comment by mrentsch65** [comment]
**Das hier macht wenig Sinn:**

![image](https://user-images.githubusercontent.com/50681355/233854898-a281dbab-08ce-46e0-9808-a63fcad4bbdc.png)

**Der Inhaltsbaum unter der SystemUnitClass muss in der Navigationsleiste angezeigt werden:**

![image](https://user-images.githubusercontent.com/50681355/233855063-6ed2d63c-e31f-4781-8fdc-652a119a2c44.png)

**Comment by sophiekirschner** [comment]
![image](https://user-images.githubusercontent.com/96117790/234212701-4d6c6c5c-c0ed-4737-924e-292a0927d61b.png)

Stellen Sie sich den Aufbau der Seite so vor?

Wir würden in dem Entwurf sowohl die systemUnitClasses, Interfaces und die RoleClasses in unterschiedlichen Reitern laden.
Außerdem würden wir die Attributnamen IdentificationData etc (die, die eine unterauswahl haben) mit in die große Navigationsleiste links verschieben.

**Comment by mrentsch65** [comment]
> > Installation ist because of IT policy not possible, certificates of the app need to be updated first:
> > ![image](https://user-images.githubusercontent.com/50681355/233730335-f0979778-e6cf-4622-aa05-6cd2c943fe74.png)
> 
> For a description of the installation please visit our [Wiki](https://github.com/robinziegler/TINF21C_Team4_Modelling_Wizard_Improvements/wiki/Instruction#add-certificate-for-the-modelling-wizard)

Das hilft aber dem Anwender nur bedingt, wenn er diese Installationshinweise  nicht findet. In dem Dialog sollte der Hinweis stehen, bzw. zumindest ein Link auf das Wiki.

**Comment by mrentsch65** [comment]
Das Überinstallieren sollte ohne vorherige manuelle Deinstallation funktionieren. Alle normalen Applikationen können das.
![image](https://user-images.githubusercontent.com/50681355/236610362-406538db-5cbf-44ac-b3c8-742ce4202bc5.png)

**Comment by maximiliantrumpp** [comment]
Vielen Dank für Ihre Rückmeldung. Wir haben versucht dieses Problem im neusten Release zu beheben. Bitte teilen Sie uns mit ob das Problem hierdurch behoben wurde. Vielen Dank.

**Comment by maximiliantrumpp** [comment]
> > > Installation ist because of IT policy not possible, certificates of the app need to be updated first:
> > > ![image](https://user-images.githubusercontent.com/50681355/233730335-f0979778-e6cf-4622-aa05-6cd2c943fe74.png)
> > 
> > 
> > For a description of the installation please visit our [Wiki](https://github.com/robinziegler/TINF21C_Team4_Modelling_Wizard_Improvements/wiki/Instruction#add-certificate-for-the-modelling-wizard)
> 
> Das hilft aber dem Anwender nur bedingt, wenn er diese Installationshinweise nicht findet. In dem Dialog sollte der Hinweis stehen, bzw. zumindest ein Link auf das Wiki.

Auf den Dialog können wir leider keinen Einfluss nehmen, dieser wird von Windows erstellt und verwaltet. Das Problem würde sich mit einem offiziellen Zertifikat lösen lassen. Die Kosten für ein offizielles Zertifikat liegen jedoch bei 200-300 Euro.
